FROM alpine
RUN apk update && apk upgrade && apk add transmission-daemon openvpn sudo
COPY rootfs.transmission /
COPY login.conf /etc/openvpn/pia/login.conf
RUN chmod +x /root/start.sh
HEALTHCHECK CMD ip a | grep -q tun0
ENTRYPOINT ["/bin/sh", "-c", "/root/start.sh"]
